//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4984
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 
namespace Intuit.Sb.Cdm.V2
{
    using System.Xml.Serialization;


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.intuit.com/sb/cdm/v2")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.intuit.com/sb/cdm/v2", IsNullable = false)]
    public partial class RestResponse
    {

        private RestResponseCompaniesMetaData[] itemsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CompaniesMetaData")]
        public RestResponseCompaniesMetaData[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.intuit.com/sb/cdm/v2")]
    public partial class RestResponseCompaniesMetaData
    {

        private RestResponseCompaniesMetaDataCompanyMetaData[] companyMetaDataField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CompanyMetaData")]
        public RestResponseCompaniesMetaDataCompanyMetaData[] CompanyMetaData
        {
            get
            {
                return this.companyMetaDataField;
            }
            set
            {
                this.companyMetaDataField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.intuit.com/sb/cdm/v2")]
    public partial class RestResponseCompaniesMetaDataCompanyMetaData
    {

        private string externalRealmIdField;

        private string qBNRegisteredCompanyNameField;

        private string sampleFileField;

        private string qBNCompanyUserAdminIdNumberField;

        private string qBNCompanyUserAdminEmailField;

        private string syncEnabledField;

        //private RestResponseCompaniesMetaDataCompanyMetaDataCustomField[] customFieldField;

        /// <remarks/>
        public string ExternalRealmId
        {
            get
            {
                return this.externalRealmIdField;
            }
            set
            {
                this.externalRealmIdField = value;
            }
        }

        /// <remarks/>
        public string QBNRegisteredCompanyName
        {
            get
            {
                return this.qBNRegisteredCompanyNameField;
            }
            set
            {
                this.qBNRegisteredCompanyNameField = value;
            }
        }

        /// <remarks/>
        public string SampleFile
        {
            get
            {
                return this.sampleFileField;
            }
            set
            {
                this.sampleFileField = value;
            }
        }

        /// <remarks/>
        public string QBNCompanyUserAdminIdNumber
        {
            get
            {
                return this.qBNCompanyUserAdminIdNumberField;
            }
            set
            {
                this.qBNCompanyUserAdminIdNumberField = value;
            }
        }

        /// <remarks/>
        public string QBNCompanyUserAdminEmail
        {
            get
            {
                return this.qBNCompanyUserAdminEmailField;
            }
            set
            {
                this.qBNCompanyUserAdminEmailField = value;
            }
        }

        /// <remarks/>
        public string SyncEnabled
        {
            get
            {
                return this.syncEnabledField;
            }
            set
            {
                this.syncEnabledField = value;
            }
        }

        ///// <remarks/>
        //[System.Xml.Serialization.XmlElementAttribute("CustomField")]
        //public RestResponseCompaniesMetaDataCompanyMetaDataCustomField[] CustomField
        //{
        //    get
        //    {
        //        return this.customFieldField;
        //    }
        //    set
        //    {
        //        this.customFieldField = value;
        //    }
        //}
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.intuit.com/sb/cdm/v2")]
    public partial class RestResponseCompaniesMetaDataCompanyMetaDataCustomField
    {

        private string nameField;

        private string valueField;

        private RestResponseCompaniesMetaDataCompanyMetaDataCustomFieldDefinitionId[] definitionIdField;

        /// <remarks/>
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DefinitionId", IsNullable = true)]
        public RestResponseCompaniesMetaDataCompanyMetaDataCustomFieldDefinitionId[] DefinitionId
        {
            get
            {
                return this.definitionIdField;
            }
            set
            {
                this.definitionIdField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.intuit.com/sb/cdm/v2")]
    public partial class RestResponseCompaniesMetaDataCompanyMetaDataCustomFieldDefinitionId
    {

        private string idDomainField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string idDomain
        {
            get
            {
                return this.idDomainField;
            }
            set
            {
                this.idDomainField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
}
